d={}

name=input("Enter Friends name :")
lang=input("Enter lanuage name :")
d.update({name:lang})
name=input("Enter Friends name :")
lang=input("Enter lanuage name :")
d.update({name:lang})
name=input("Enter Friends name :")
lang=input("Enter lanuage name :")
d.update({name:lang})
name=input("Enter Friends name :")
lang=input("Enter lanuage name :")
d.update({name:lang})
print(d)